
%% EE361 HW#5

%% NAME: _MICHAEL FARADAY_
%% STUDENT NUMBER: 123456


%%
% change your .m file name to the following:
% name_surname_ID_hw5

% please add axis names, legends and titles
% in all your plots

% examine the whole template before you start

%%
% PARAMETERS
%define the constant parameters

% drag


% friction


% gravity


% train


% motor
% rated values


%%
%use the following sytax in all your derivations and expressions
%%
% $z=sqrt(x^2+y^2)$


%%
%Part I

%%
% Part I-a

Ts = 1; % time step (seconds)
t = 0:Ts:1e3; % time vector
Num = numel(t);

% define all the vectors asked in the homework
Fnet = zeros(1,Num);
acceleration = zeros(1,Num);
velocity = zeros(1,Num);
position = zeros(1,Num);
Ea = zeros(1,Num);
Ia = zeros(1,Num);
Vt = zeros(1,Num);
efficiency = zeros(1,Num);


%%
% part a-(i)

% Trated = ?


%%
% HINTS:

% Utilization of a "while" loop for time iteration is a better solution
% than using a "for" loop since the final time is not known

% Add a statement to your loop which finds out that the rated speed is
% reached (by using "break"). Define a parameter "final" which corresponds
% to the final point of the time array.
% This will be useful for the plots (time-axis limits)

% In your loop, just like in HW#4, implement a subroutine which calculates
% the next velocity and position

% All the asked parameters will be found in this loop
% In all parts, same kind of solution can be used


% YOU MUST WRITE THE EXPRESSIONS AND NECESSARY EXPLANATIONS HERE
% WHICH WILL BE USED IN THE CALCULATIONS

%...
%insert your code here (expression)
%explanations
%...


%%

% be careful about the initial condition (speed)
% be careful about the direction of net force and acceleration


% UNCOMMENT THE FOLLOWING
%k = 0;
%while (1)
    %k = k+1;
    
    % Ftrain = ? % force generated by the traction system
    % Fdrag = ? % drag force
    % Ffriction = ? % friction force
    % Fnet(k) = ? % net force
    
    % acceleration(k) = ?
    % velocity(k+1) = ?
    % position(k+1) = ?
    
    % Ea(k) = ?
    % Ia(k) = ?
    % Vt(k) = ?
    
    % efficiency(k) = ?
    
    %if velocity(k) >= ?
    %    ??
    %    ??
    %end
%end


%%
% part a-(ii)


% UNCOMMENT THE FOLLOWING
% figure;
% plot(t,Fnet,'b -','Linewidth',1.5);
% grid on;
% xlim([0,t(final)]);
% set(gca,'FontSize',12);
% xlabel('Time (s)');
% ylabel('Net Force (N)')
% title('Net Force Against Time');

%your graph will be here


%%
% part a-(iii)

% UNCOMMENT THE FOLLOWING
% figure;
% subplot(3,1,1);
% plot(t,acceleration,'b -','Linewidth',1.5);
% grid on;
% set(gca,'FontSize',12);
% xlim([0,t(final)]);
% ylabel('Acceleration (m/s^2)');
% 
% subplot(3,1,2);
% plot(t,velocity*3.6,'r -','Linewidth',1.5);
% grid on;
% set(gca,'FontSize',12);
% xlim([0,t(final)]);
% ylabel('Velocity (km/h)');
% 
% subplot(3,1,3);
% plot(t,position,'k -','Linewidth',1.5);
% grid on;
% set(gca,'FontSize',12);
% xlim([0,t(final)]);
% xlabel('Time (s)');
% ylabel('Position (m)');


%your graph will be here


%%
% part a-(iv)

%insert your code here (subplot)

%your graph will be here


%%
% part a-(v)

%insert your code here (plot)

%your graph will be here


%%
% part a-(vi)

%insert your code here (display)

%your result will be here


%%
% part a-(vii)

%insert your code here (display)

%your result will be here


%%
% part a-(viii)

%Insert
%your
%comment
%here
%and
%there
%...



%%
% Part I-b

Ts = 1; % time step (seconds)
t = 0:Ts:1e3; % time vector
Num = numel(t);

% define all the vectors asked in the homework
Fnet = zeros(1,Num);
acceleration = zeros(1,Num);
velocity = zeros(1,Num);
position = zeros(1,Num);
Ea = zeros(1,Num);
Ia = zeros(1,Num);
Vt = zeros(1,Num);
efficiency = zeros(1,Num);


% YOU MUST WRITE THE EXPRESSIONS AND NECESSARY EXPLANATIONS HERE
% WHICH WILL BE USED IN THE CALCULATIONS

%...
%insert your code here (expression)
%explanations
%...


%%

% be careful about the initial condition (speed)
% be careful about the direction of net force and acceleration


% UNCOMMENT THE FOLLOWING
%k = 0;
%while (1)
    %k = k+1;
    
    % Ftrain = ? % force generated by the traction system
    % Fdrag = ? % drag force
    % Ffriction = ? % friction force
    % Fnet(k) = ? % net force
    
    % acceleration(k) = ?
    % velocity(k+1) = ?
    % position(k+1) = ?
    
    % Ea(k) = ?
    % Ia(k) = ?
    % Vt(k) = ?
    
    % efficiency(k) = ?
    
    %if velocity(k) >= ?
    %    ??
    %    ??
    %end
%end


%%
% part b-(i)

%insert your code here (plot)

%your graph will be here


%%
% part b-(ii)

%insert your code here (subplot)

%your graph will be here


%%
% part b-(iii)

%insert your code here (subplot)

%your graph will be here


%%
% part b-(iv)

%insert your code here (plot)

%your graph will be here


%%
% part b-(v)

%insert your code here (display)

%your result will be here


%%
% part b-(vi)

%insert your code here (display)

%your result will be here


%%
% part b-(vii)

%Insert
%your
%comment
%here
%and
%there
%...



%%
% Part II

Ts = 1; % time step (seconds)
t = 0:Ts:1e5; % time vector
Num = numel(t);

% define all the vectors asked in the homework
Fnet = zeros(1,Num);
acceleration = zeros(1,Num);
velocity = zeros(1,Num);
position = zeros(1,Num);
Ea = zeros(1,Num);
Ia = zeros(1,Num);
Vt = zeros(1,Num);
efficiency = zeros(1,Num);


% YOU MUST WRITE THE EXPRESSIONS AND NECESSARY EXPLANATIONS HERE
% WHICH WILL BE USED IN THE CALCULATIONS

%...
%insert your code here (expression)
%explanations
%...


%%

% be careful about the initial condition (speed)
% be careful about the direction of net force and acceleration


% UNCOMMENT THE FOLLOWING
% k = 0;
% while (1)
%     k = k+1;
    
    % Ftrain = ? % force generated by the traction system
    % Fdrag = ? % drag force
    % Ffriction = ? % friction force
    % Fnet(k) = ? % net force
    
    % acceleration(k) = ?
    % velocity(k+1) = ?
    % position(k+1) = ?
    
    % Ea(k) = ?
    % Ia(k) = ?
    % Vt(k) = ?
    
    % efficiency(k) = ?
    
    %if position(k) >= ?
    %    ??
    %    ??
    %end
% end


%%
% part II-(i)

%insert your code here (plot)

%your graph will be here


%%
% part II-(ii)

%insert your code here (subplot)

%your graph will be here


%%
% part II-(iii)

%insert your code here (subplot)

%your graph will be here


%%
% part II-(iv)

%insert your code here (plot)

%your graph will be here


%%
% part II-(v)

%insert your code here (display)

%your result will be here


%%
% part II-(vi)

%Insert
%your
%comment
%here
%and
%there
%...




%%
% Part III

Ts = 1; % time step (seconds)
t = 0:Ts:1e5; % time vector
Num = numel(t);

% define all the vectors asked in the homework
Fnet = zeros(1,Num);
acceleration = zeros(1,Num);
velocity = zeros(1,Num);
position = zeros(1,Num);
Ea = zeros(1,Num);
Ia = zeros(1,Num);
Vt = zeros(1,Num);
efficiency = zeros(1,Num);


% YOU MUST WRITE THE EXPRESSIONS AND NECESSARY EXPLANATIONS HERE
% WHICH WILL BE USED IN THE CALCULATIONS

%...
%insert your code here (expression)
%explanations
%...


%%

% be careful about the initial condition (speed)
% be careful about the direction of net force and acceleration


% UNCOMMENT THE FOLLOWING
% k = 0;
% while (1)
%     k = k+1;
    
    % Ftrain = ? % force generated by the traction system
    % Fdrag = ? % drag force
    % Ffriction = ? % friction force
    % Fnet(k) = ? % net force
    
    % acceleration(k) = ?
    % velocity(k+1) = ?
    % position(k+1) = ?
    
    % Ea(k) = ?
    % Ia(k) = ?
    % Vt(k) = ?
    
    % efficiency(k) = ?
    
    %if position(k) >= ?
    %    ??
    %    ??
    %end
% end


%%
% part III-(i)

%insert your code here (plot)

%your graph will be here


%%
% part III-(ii)

%insert your code here (subplot)

%your graph will be here


%%
% part III-(iii)

%insert your code here (subplot)

%your graph will be here


%%
% part III-(iv)

%insert your code here (plot)

%your graph will be here


%%
% part III-(v)

%insert your code here (display)

%your result will be here


%%
% part III-(vi)

%Insert
%your
%comment
%here
%and
%there
%...



%% After you finished
% Run the following command from Matlab terminal (command window)
% generate a report of your .m file as pdf and
% ONLY upload the PDF file to ODTUClass.

%publish('name_surname_ID_hw5.m', 'pdf')

